name: marvel_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.6
  intl: ^0.19.0

  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.1.0
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.3
  repository:
    path: packages/repository

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png

  generate: true
